# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CDAdsSwiftExample' do
    pod 'Chalkdigital-Mobile-Ads-SDK', '~>1.0.5'
end

